### ISSUE TITLE
Clean UP & Dockerization eos9tyg

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos9tyg#2]

**Comment by GemmaTuron** [comment]
Hi @emmakodes 

I have merged your PR!

**Comment by emmakodes** [comment]
Okay @GemmaTuron I am monitoring the workflows to be sure they work.

**Comment by emmakodes** [comment]
Hello @GemmaTuron `pip install scikit-learn==0.22` fails on linux/arm64 as it is not compatible on linux/arm64.

```
#8 826.8 Building wheels for collected packages: scikit-learn
#8 826.8   Building wheel for scikit-learn (setup.py): started
#8 826.8   Building wheel for scikit-learn (setup.py): finished with status 'error'
#8 826.8   error: subprocess-exited-with-error
#8 826.8   
#8 826.8   × python setup.py bdist_wheel did not run successfully.
#8 826.8   │ exit code: 1
#8 826.8   ╰─> [23 lines of output]
#8 826.8       Partial import of sklearn during the build process.
#8 826.8       Traceback (most recent call last):
#8 826.8         File "/tmp/pip-install-3rfp49vw/scikit-learn_c60e9dbc955d444399f5a43bddd51b78/setup.py", line 195, in check_package_status
#8 826.8           module = importlib.import_module(package)
#8 826.8         File "/usr/bin/conda/envs/eos9tyg/lib/python3.7/importlib/__init__.py", line 127, in import_module
#8 826.8           return _bootstrap._gcd_import(name[level:], package, level)
#8 826.8         File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
#8 826.8         File "<frozen importlib._bootstrap>", line 983, in _find_and_load
#8 826.8         File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
#8 826.8       ModuleNotFoundError: No module named 'scipy'
#8 826.8       Traceback (most recent call last):
#8 826.8         File "<string>", line 36, in <module>
#8 826.8         File "<pip-setuptools-caller>", line 34, in <module>
#8 826.8         File "/tmp/pip-install-3rfp49vw/scikit-learn_c60e9dbc955d444399f5a43bddd51b78/setup.py", line 303, in <module>
#8 826.8           setup_package()
#8 826.8         File "/tmp/pip-install-3rfp49vw/scikit-learn_c60e9dbc955d444399f5a43bddd51b78/setup.py", line 293, in setup_package
#8 826.8           check_package_status('scipy', SCIPY_MIN_VERSION)
#8 826.8         File "/tmp/pip-install-3rfp49vw/scikit-learn_c60e9dbc955d444399f5a43bddd51b78/setup.py", line 221, in check_package_status
#8 826.8           .format(package, req_str, instructions))
#8 826.8       ImportError: scipy is not installed.
#8 826.8       scikit-learn requires scipy >= 0.17.0.
#8 826.8       Installation instructions are available on the scikit-learn website: http://scikit-learn.org/stable/install.html
#8 826.8       
#8 826.8       [end of output]
#8 826.8   
#8 826.8   note: This error originates from a subprocess, and is likely not a problem with pip.
#8 826.8   ERROR: Failed building wheel for scikit-learn
#8 826.8   Running setup.py clean for scikit-learn
#8 826.8 Failed to build scikit-learn
#8 826.8 Installing collected packages: scipy, joblib, scikit-learn
#8 826.8   Running setup.py install for scikit-learn: started
#8 826.8   Running setup.py install for scikit-learn: finished with status 'error'
#8 826.8   error: subprocess-exited-with-error
#8 826.8   
#8 826.8   × Running setup.py install for scikit-learn did not run successfully.
#8 826.8   │ exit code: 1
#8 826.8   ╰─> [22 lines of output]
#8 826.8       Partial import of sklearn during the build process.
#8 826.8       Traceback (most recent call last):
#8 826.8         File "/tmp/pip-install-3rfp49vw/scikit-learn_c60e9dbc955d444399f5a43bddd51b78/sklearn/_build_utils/__init__.py", line 32, in _check_cython_version
#8 826.8           import Cython
#8 826.8       ModuleNotFoundError: No module named 'Cython'
#8 826.8       
#8 826.8       During handling of the above exception, another exception occurred:
#8 826.8       
#8 826.8       Traceback (most recent call last):
#8 826.8         File "<string>", line 36, in <module>
#8 826.8         File "<pip-setuptools-caller>", line 34, in <module>
#8 826.8         File "/tmp/pip-install-3rfp49vw/scikit-learn_c60e9dbc955d444399f5a43bddd51b78/setup.py", line 303, in <module>
#8 826.8           setup_package()
#8 826.8         File "/tmp/pip-install-3rfp49vw/scikit-learn_c60e9dbc955d444399f5a43bddd51b78/setup.py", line 299, in setup_package
#8 826.8           setup(**metadata)
#8 826.8         File "/usr/bin/conda/envs/eos9tyg/lib/python3.7/site-packages/numpy/distutils/core.py", line 135, in setup
#8 826.8           config = configuration()
#8 826.8         File "/tmp/pip-install-3rfp49vw/scikit-learn_c60e9dbc955d444399f5a43bddd51b78/setup.py", line 180, in configuration
#8 826.8           _check_cython_version()
#8 826.8         File "/tmp/pip-install-3rfp49vw/scikit-learn_c60e9dbc955d444399f5a43bddd51b78/sklearn/_build_utils/__init__.py", line 35, in _check_cython_version
#8 826.8           raise ModuleNotFoundError(message)
#8 826.8       ModuleNotFoundError: Please install Cython with a version >= 0.28.5 in order to build a scikit-learn from source.
#8 826.8       [end of output]
#8 826.8   
#8 826.8   note: This error originates from a subprocess, and is likely not a problem with pip.
#8 826.8 error: legacy-install-failure
#8 826.8 
#8 826.8 × Encountered error while trying to install package.
#8 826.8 ╰─> scikit-learn
```

 I have made a pull request to fix how it is installed in the dockerfile to `conda install -c conda-forge scikit-learn=1.0.2` as recommended [here](https://github.com/scikit-learn/scikit-learn/issues/17800) to work on linux/arm64

**Comment by GemmaTuron** [comment]
Hi Emmanuel, 

Does the rest of the things work with such a big change in versions (from 0.22 to 1.0.2)

**Comment by emmakodes** [comment]
Yes, @GemmaTuron I fetched and made predictions successfully and it should push to DockerHub

**Comment by miquelduranfrigola** [comment]
Hi @emmakodes and @GemmaTuron -

I have updated workflows for this model, let's see if it works: https://github.com/ersilia-os/eos9tyg/actions/

**Comment by miquelduranfrigola** [comment]
@GemmaTuron - This model seems to be resolved, please check

**Comment by GemmaTuron** [comment]
Before closing this issue I want to make sure that we are able to provide the output as a .csv file.
@emmakodes can you check the model testing issue and let us know?

**Comment by emmakodes** [comment]
Okay @GemmaTuron let me test again
